// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
  };

  type GalleryTableRow = {
    id: string;
    title: string;
    description: string;
    thumbnail: string;
    html: string;
    css: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
    };
    write: {
      email: string;
      password: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllGalleryViewRow = {
    read: {
      id: string;
      title: string;
      description: string;
      thumbnail: string;
      html: string;
      css: string;
    };
    write: {
      title: string;
      description: string;
      thumbnail: string;
      html: string;
      css: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type CollaboratorsViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
    };
    write: {
      email: string;
      password: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    allGallery: AllGalleryViewRow;
    collaborators: CollaboratorsViewRow;
  };
}
